#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : totem-pl-parser
Version  : 3.26.0
Release  : 3
URL      : https://download.gnome.org/sources/totem-pl-parser/3.26/totem-pl-parser-3.26.0.tar.xz
Source0  : https://download.gnome.org/sources/totem-pl-parser/3.26/totem-pl-parser-3.26.0.tar.xz
Summary  : Totem Playlist Parser library, mini version
Group    : Development/Tools
License  : LGPL-2.1
Requires: totem-pl-parser-data
Requires: totem-pl-parser-lib
Requires: totem-pl-parser-locales
BuildRequires : glibc-bin
BuildRequires : gmime-dev
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : libxml2-dev
BuildRequires : meson
BuildRequires : ninja
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : python3

%description
_|_ __|_ _ ._ _
|_(_)|_(/_| | |
playlist parser
totem-pl-parser is a simple GObject-based library to parse a host of
playlist formats, as well as save those

%package data
Summary: data components for the totem-pl-parser package.
Group: Data

%description data
data components for the totem-pl-parser package.


%package dev
Summary: dev components for the totem-pl-parser package.
Group: Development
Requires: totem-pl-parser-lib
Requires: totem-pl-parser-data
Provides: totem-pl-parser-devel

%description dev
dev components for the totem-pl-parser package.


%package lib
Summary: lib components for the totem-pl-parser package.
Group: Libraries
Requires: totem-pl-parser-data

%description lib
lib components for the totem-pl-parser package.


%package locales
Summary: locales components for the totem-pl-parser package.
Group: Default

%description locales
locales components for the totem-pl-parser package.


%prep
%setup -q -n totem-pl-parser-3.26.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1505398229
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain  builddir
ninja -v -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang totem-pl-parser

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/TotemPlParser-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/totem-pl-parser/1/plparser/totem-pl-parser-builtins.h
/usr/include/totem-pl-parser/1/plparser/totem-pl-parser-features.h
/usr/include/totem-pl-parser/1/plparser/totem-pl-parser-mini.h
/usr/include/totem-pl-parser/1/plparser/totem-pl-parser.h
/usr/include/totem-pl-parser/1/plparser/totem-pl-playlist.h
/usr/lib64/libtotem-plparser-mini.so
/usr/lib64/libtotem-plparser.so
/usr/lib64/pkgconfig/totem-plparser-mini.pc
/usr/lib64/pkgconfig/totem-plparser.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtotem-plparser-mini.so.18
/usr/lib64/libtotem-plparser-mini.so.18.1.1
/usr/lib64/libtotem-plparser.so.18
/usr/lib64/libtotem-plparser.so.18.1.1

%files locales -f totem-pl-parser.lang
%defattr(-,root,root,-)

