#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : totem-pl-parser
Version  : 3.26.3
Release  : 9
URL      : https://download.gnome.org/sources/totem-pl-parser/3.26/totem-pl-parser-3.26.3.tar.xz
Source0  : https://download.gnome.org/sources/totem-pl-parser/3.26/totem-pl-parser-3.26.3.tar.xz
Summary  : Totem Playlist Parser library
Group    : Development/Tools
License  : LGPL-2.0
Requires: totem-pl-parser-data = %{version}-%{release}
Requires: totem-pl-parser-lib = %{version}-%{release}
Requires: totem-pl-parser-license = %{version}-%{release}
Requires: totem-pl-parser-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gmime-dev
BuildRequires : gobject-introspection-dev
BuildRequires : libarchive-dev
BuildRequires : libxml2-dev
BuildRequires : pkgconfig(libsoup-2.4)

%description
_|_ __|_ _ ._ _
|_(_)|_(/_| | |
playlist parser
totem-pl-parser is a simple GObject-based library to parse a host of
playlist formats, as well as save those

%package data
Summary: data components for the totem-pl-parser package.
Group: Data

%description data
data components for the totem-pl-parser package.


%package dev
Summary: dev components for the totem-pl-parser package.
Group: Development
Requires: totem-pl-parser-lib = %{version}-%{release}
Requires: totem-pl-parser-data = %{version}-%{release}
Provides: totem-pl-parser-devel = %{version}-%{release}
Requires: totem-pl-parser = %{version}-%{release}

%description dev
dev components for the totem-pl-parser package.


%package lib
Summary: lib components for the totem-pl-parser package.
Group: Libraries
Requires: totem-pl-parser-data = %{version}-%{release}
Requires: totem-pl-parser-license = %{version}-%{release}

%description lib
lib components for the totem-pl-parser package.


%package license
Summary: license components for the totem-pl-parser package.
Group: Default

%description license
license components for the totem-pl-parser package.


%package locales
Summary: locales components for the totem-pl-parser package.
Group: Default

%description locales
locales components for the totem-pl-parser package.


%prep
%setup -q -n totem-pl-parser-3.26.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557024576
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/totem-pl-parser
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/totem-pl-parser/COPYING.LIB
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang totem-pl-parser

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/TotemPlParser-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/totem-pl-parser/1/plparser/totem-pl-parser-builtins.h
/usr/include/totem-pl-parser/1/plparser/totem-pl-parser-features.h
/usr/include/totem-pl-parser/1/plparser/totem-pl-parser-mini.h
/usr/include/totem-pl-parser/1/plparser/totem-pl-parser.h
/usr/include/totem-pl-parser/1/plparser/totem-pl-playlist.h
/usr/lib64/libtotem-plparser-mini.so
/usr/lib64/libtotem-plparser.so
/usr/lib64/pkgconfig/totem-plparser-mini.pc
/usr/lib64/pkgconfig/totem-plparser.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtotem-plparser-mini.so.18
/usr/lib64/libtotem-plparser-mini.so.18.1.4
/usr/lib64/libtotem-plparser.so.18
/usr/lib64/libtotem-plparser.so.18.1.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/totem-pl-parser/COPYING.LIB

%files locales -f totem-pl-parser.lang
%defattr(-,root,root,-)

